version: '3'
services:
  app-java:
    container_name: app_java_box
    image: openjdk:17-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - DB_HOST=mysql
      - DB_URL=${MYSQL_URL}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mysql
    networks:
      - code-network

  mysql:
    container_name: mysql_box
    restart: always
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_DUMPS}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - code-network

networks:
  code-network:
    driver: bridge